export const lesson1 = [
  { key: "a", position: "left-[50px]", keyCode: 65, location: 0 },
  { key: "s", position: "left-[100px]", keyCode: 83, location: 0 },
  { key: "D", position: "left-[150px]", keyCode: 68, location: 1 },
  { key: "f", position: "left-[200px]", keyCode: 70, location: 0 },
  { key: "g", position: "left-[250px]", keyCode: 71, location: 0 },
  { key: "h", position: "left-[300px]", keyCode: 72, location: 0 },
  { key: "j", position: "left-[350px]", keyCode: 74, location: 0 },
  { key: "k", position: "left-[400px]", keyCode: 75, location: 0 },
  { key: "L", position: "left-[450px]", keyCode: 76, location: 2 },
];
export const rows = [
  [
    { key: "`", position: "left-[0px]", keyCode: 192, location: 0 },
    { key: "1", position: "left-[50px]", keyCode: 49, location: 0 },
    { key: "2", position: "left-[100px]", keyCode: 50, location: 0 },
    { key: "3", position: "left-[150px]", keyCode: 51, location: 0 },
    { key: "4", position: "left-[200px]", keyCode: 52, location: 0 },
    { key: "5", position: "left-[250px]", keyCode: 53, location: 0 },
    { key: "6", position: "left-[300px]", keyCode: 54, location: 0 },
    { key: "7", position: "left-[350px]", keyCode: 55, location: 0 },
    { key: "8", position: "left-[400px]", keyCode: 56, location: 0 },
    { key: "9", position: "left-[450px]", keyCode: 57, location: 0 },
    { key: "0", position: "left-[500px]", keyCode: 48, location: 0 },
    { key: "-", position: "left-[550px]", keyCode: 173, location: 0 },
    { key: "=", position: "left-[600px]", keyCode: 61, location: 0 },
    {
      key: "delete",
      position: "left-[650px]",
      size: "w-[90px]",
      keyCode: 8,
      location: 0,
    },
  ],
  [
    {
      key: "tab",
      position: "left-[0px]",
      size: "w-[90px]",
      keyCode: 9,
      location: 0,
    },
    { key: "q", position: "left-[50px]", keyCode: 81, location: 0 },
    { key: "w", position: "left-[100px]", keyCode: 87, location: 0 },
    { key: "e", position: "left-[150px]", keyCode: 69, location: 0 },
    { key: "r", position: "left-[200px]", keyCode: 82, location: 0 },
    { key: "t", position: "left-[250px]", keyCode: 84, location: 0 },
    { key: "y", position: "left-[300px]", keyCode: 89, location: 0 },
    { key: "u", position: "left-[350px]", keyCode: 85, location: 0 },
    { key: "i", position: "left-[400px]", keyCode: 73, location: 0 },
    { key: "o", position: "left-[450px]", keyCode: 79, location: 0 },
    { key: "p", position: "left-[500px]", keyCode: 80, location: 0 },
    { key: "[", position: "left-[550px]", keyCode: 219, location: 0 },
    { key: "]", position: "left-[600px]", keyCode: 221, location: 0 },
    { key: "\\", position: "left-[650px]", keyCode: 220, location: 0 },
  ],
  [
    {
      key: "Caps lock",
      position: "left-[0px]",
      size: "w-24",
      keyCode: 20,
      location: 0,
    },
    { key: "a", position: "left-[50px]", keyCode: 65, location: 0 },
    { key: "s", position: "left-[100px]", keyCode: 83, location: 0 },
    { key: "d", position: "left-[150px]", keyCode: 68, location: 0 },
    { key: "f", position: "left-[200px]", keyCode: 70, location: 0 },
    { key: "g", position: "left-[250px]", keyCode: 71, location: 0 },
    { key: "h", position: "left-[300px]", keyCode: 72, location: 0 },
    { key: "j", position: "left-[350px]", keyCode: 74, location: 0 },
    { key: "k", position: "left-[400px]", keyCode: 75, location: 0 },
    { key: "l", position: "left-[450px]", keyCode: 76, location: 0 },
    { key: ";", position: "left-[500px]", keyCode: 59, location: 0 },
    { key: "'", position: "left-[550px]", keyCode: 222, location: 0 },
    {
      key: "enter",
      position: "left-[600px]",
      size: "w-24",
      keyCode: 13,
      location: 0,
    },
  ],
  [
    {
      key: "Shift",
      position: "left-[0px]",
      size: "w-[123px]",
      keyCode: 16,
      location: 1,
    },
    { key: "z", position: "left-[50px]", keyCode: 90, location: 0 },
    { key: "x", position: "left-[100px]", keyCode: 88, location: 0 },
    { key: "c", position: "left-[150px]", keyCode: 67, location: 0 },
    { key: "v", position: "left-[200px]", keyCode: 86, location: 0 },
    { key: "b", position: "left-[250px]", keyCode: 66, location: 0 },
    { key: "n", position: "left-[300px]", keyCode: 78, location: 0 },
    { key: "m", position: "left-[350px]", keyCode: 77, location: 0 },
    { key: ",", position: "left-[400px]", keyCode: 188, location: 0 },
    { key: ".", position: "left-[450px]", keyCode: 190, location: 0 },
    { key: "/", position: "left-[500px]", keyCode: 191, location: 0 },
    {
      key: "Shift",
      position: "left-[550px]",
      size: "w-[123px]",
      keyCode: 16,
      location: 2,
    },
  ],
  [
    {
      key: "ctrl",
      position: "left-[0px]",
      size: "w-16",
      keyCode: 17,
      location: 3,
    },
    {
      key: "alt",
      position: "left-[50px]",
      size: "w-16",
      keyCode: 18,
      location: 3,
    },
    {
      key: " ",
      position: "left-[150px]",
      size: "w-[500px]",
      keyCode: 32,
      location: 0,
    },
    {
      key: "alt",
      position: "left-[350px]",
      size: "w-16",
      keyCode: 18,
      location: 3,
    },
    {
      key: "ctrl",
      position: "left-[450px]",
      size: "w-16",
      keyCode: 17,
      location: 3,
    },
  ],
];
